### ISSUE TITLE
ResponseEntityWriterContributor should not terminate the pipeline, this is the job for the EndContributor.

### ISSUE THREAD

**Issue by MarkKharitonov** [openrasta/openrasta-core#10]
As of now, it is impossible to register a pipeline contributor to compress the response, because such a contributor belongs between `KnownStages.IResponseCoding` and `KnownStages.IEnd`, but `ResponseEntityWriterContributor` implementing the `KnownStages.IResponseCoding` stage terminates the pipeline!

See https://groups.google.com/d/topic/openrasta/_aCXNQAXEFw/discussion for the details.

Thanks.

**Comment by serialseb** [comment]
Hi!

Thanks for contributing, it's awesome! 😎

After reviewing, the pipeline in 2.6x no longer termintes after response entity writing, Finished has been removed, and IEnd is only a marker. Entity stream disposers are now done as the last step in the cleanup phase. I think this solves all those problems.

As we are trying to keep our backlog fresh, and as this has not been updated for a while, I'm closing this issue.

If you feel this was closed by mistake, or that it is still relevant, don't hesitate to comment and reopen it, and we'll re-evaluate.

Live long, and proper! 🖖🏽
