### ISSUE TITLE
Add this repo to up-for-grabs.net

### ISSUE THREAD

**Issue by serialseb** [openrasta/openrasta-core#102]
There's already a label, need to add a project yml file over at https://github.com/up-for-grabs/up-for-grabs.net

**Comment by gshackles** [comment]
I just threw a quick PR up in their repo for it: https://github.com/up-for-grabs/up-for-grabs.net/pull/623

**Comment by gshackles** [comment]
Merged and live, happy to make any changes as needed 😄 http://up-for-grabs.net/#/tags/rest

![image](https://cloud.githubusercontent.com/assets/196182/26465931/f4187b7a-415a-11e7-8049-f7b325d620be.png)

**Comment by serialseb** [comment]
Awesome, thanks!
