### ISSUE TITLE
Operations no longer available in pipeline data

### ISSUE THREAD

**Issue by gshackles** [openrasta/openrasta-core#109]
We have a pipeline contributor that checks attributes for a request's operations in order to do some permission checks. Previously we accessed it like this:

```
var operations = context.PipelineData["__OR_PIPELINE_Operations"] as IEnumerable<IOperation>;
```

After updating to ci-1119, `__OR_PIPELINE_Operations` is no longer available in `PipelineData`:

![image](https://user-images.githubusercontent.com/196182/27546591-38345b66-5a61-11e7-8adb-17d55d72f43e.png)

**Comment by serialseb** [comment]
Fixed in ebe2c2c
