### ISSUE TITLE
Response Content-Type header incorrectly contains the quality qualifier.

### ISSUE THREAD

**Issue by MarkKharitonov** [openrasta/openrasta-core#13]
Hi, here is a response I get from OpenRasta:

```
HTTP/1.1 200 OK
Content-Length: 189
Content-Type: application/xml; q="0,9"
Server: Microsoft-HTTPAPI/2.0
Date: Mon, 01 Aug 2011 08:43:37 GMT

<?xml version="1.0" encoding="utf-8"?>
<Home xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Title>Welcome home.</Title>
</Home>
```

Notice the `Content-Type` header. It should only have **application/xml**, without the quality part, having which there makes it more difficult to match deserializer based on the Content-Type.

The funny thing is that I am sure I have seent someone reporting this issue and Seb answering him that it is a bug and it was fixed. Well, it is not fixed in openrasta-core.

**Comment by serialseb** [comment]
Fixed in other parts of the code.
