### ISSUE TITLE
OpenRasta.IO.HistoryStream breaks XmlSerializer by having CanSeek as true, but the Length property throwing an exception.

### ISSUE THREAD

**Issue by MarkKharitonov** [openrasta/openrasta-core#14]
It blows `XmlSerializerCodec` on reading POST payload in XML, because the underlying `System.Xml.XmlReader` attempts to access the stream `Length`, if the stream is seekable.

The problem is that `LengthTrackingStream` forwards the `Length` request to the underlying stream, because of `CanSeek` being `true`. But even if `LengthTrackingStream` knew not to forward the request, the length known to it at that point is 0.

I do not know the correct fix to it - setting `CanSeek` to `false` seems to be dangerous, since I am unaware of all the implications.
So, I return the buffer size as the stream `Length` property value. It works, because `XmlReader` only needs it to calculate the buffer size. I will wait for the "official" fix.

**Comment by serialseb** [comment]
Hi there.

Thanks for reporting this issue! It's awesome of you to have taken the time.

It seems that this issue has been superseded by #101, so in the interest of keeping our backlog lean ⛅, I'm closing the issue in favour of the other one.

If you feel this is not right, don't hesitate to comment and/or reopen the issue.

Thanks!
