### ISSUE TITLE
Using a content type extension does not force the codec when an error happens

### ISSUE THREAD

**Issue by MarkKharitonov** [openrasta/openrasta-core#15]
Hi, here is my scenario:
- I have registered one xml codec for `object` (making it the default xml codec) and yet another xml codec for `IList<Error>` making it the xml codec for exception responses returned on HTTP error 500.
- There is a request, which returns HTTP error 500.
- The URL used in the request includes the **xml** media type extension in order to specifically ask for an XML response.

The net result is that the error response is not returned as XML. Why? Because of two things:
- the `AbortPipeline` method nullifies the `context.PipelineData.ResponseCodec` property set by `ContentTypeExtensionUriDecorator`
- `ResponseEntityCodecResolverContributor` ignores the `context.Response.Entity.ContentType` property, again set by `ContentTypeExtensionUriDecorator`

I have no claims towards the `AbortPipeline` method - the resource has changed, hence the decisions made until now as to the response codec may be wrong. But, `context.Response.Entity.ContentType` is correct and there is no reason for `ResponseEntityCodecResolverContributor` to ignore it.

So, I fixed it by replacing this code (inside `ResponseEntityCodecResolverContributor`):

```
string acceptHeader = context.Request.Headers[HEADER_ACCEPT];
```

with the following:

```
string acceptHeader =
     context.Response.Entity.ContentType == null ?
     context.Request.Headers[HEADER_ACCEPT] :
     context.Response.Entity.ContentType.MediaType;
```

And everything started working as expected.

BTW, there is a TODO comment in `ContentTypeExtensionUriDecorator.Apply`:

```
// TODO: Check if this still works.
entity.ContentType = _selectedCodec.MediaType;
```

The results of the check - no, it does not work until this bug is fixed.

**Comment by serialseb** [comment]
Apologies for being 9 years late, however the extension issue is now fixed, however slightly differently. We persist the extension when we capture it inbound, and we then use that to filter the right codec whenever an error is dispatched. It's a bit hacky but the file type extension will be rewritten differently in the future. This allow unblocking the existing scenario while adding a bit of code coverage.
