### ISSUE TITLE
Curly braces are removed from URL parameters

### ISSUE THREAD

**Issue by JornWildt** [openrasta/openrasta-core#180]
Given a URL registration like this:

    AtUrl(""parties?cvrcpr={cvrcpr}&cvr_p={cvr_p}")

and a handler like this:

    public object GetByCvrcpr(string cvrcpr, string cvr_p = null)

Why is `cvr_p` passed as the value "cvr_p" when the URL value is "{cvr_p}"?

Background: this resource started out as a single parameter `cvrcpr` resource. Now I have added `cvr_p` as an extra parameter and want to handle old clients that simply replaces `cvrcpr` with something using string replacement - leaving "cvr_p={cvr_p}" untouched in the URL (clients are supposed to lookup this URL template at runtime, not compile-time).

So I would expect OpenRasta to pass "{cvr_p}" as the raw value from the URL ... but I can see that I get "cvr_p" without the curly braces.

Bug or feature? Seems odd to me :-)

**Comment by serialseb** [comment]
I'm not sure I understand. Can you show the example URIs that come in and the value of the parameters when the handler gets called? And also what version is affected would be awesome. And if  you're feeling generous, a code repro would be brilliant!

**Comment by JornWildt** [comment]
URL as entered in the browser:

    https://xxx.xx.xx/.../parties?cvrcpr={cvrcpr}&cvr_p={cvr_p}

Code:

    [HttpOperation("GET", ForUriName = "ByCvrcpr")]
    public object GetByCvrcpr(string cvrcpr, string cvr_p = null)

Values found in code:

    cvrcpr = "cvrcpr"
    cvr_p = "cvr_p"

Expected values:

    cvrcpr = "{cvrcpr}"
    cvr_p = "{cvr_p}"

OpenRasta output:

62-[2019-08-21 12:33:40Z] Start(1) Entering OpenRastaRewriterHandler: Rewriting to original path
    62-[2019-08-21 12:33:40Z] Start(1) Entering OpenRastaIntegratedHandler: Request for https://xxx.xx.xx/.../parties?cvrcpr={cvrcpr}&cvr_p={cvr_p}
        62-[2019-08-21 12:33:40Z] Verbose(0) Incoming host request for https://xxx.xx.xx/.../parties?cvrcpr={cvrcpr}&cvr_p={cvr_p}
        62-[2019-08-21 12:33:40Z] Verbose(0) Adding communication context data
        62-[2019-08-21 12:33:40Z] Start(1) Entering PipelineRunner: Executing contributor HandlerResolverContributor.ResolveHandler
        62-[2019-08-21 12:33:40Z] Stop(1) Exiting PipelineRunner
        62-[2019-08-21 12:33:40Z] Start(1) Entering PipelineRunner: Executing contributor OperationCreatorContributor.CreateOperations
            62-[2019-08-21 12:33:40Z] Verbose(0) Created operation named GetById with signature PartyHandler::GetById(Int32 id)
            62-[2019-08-21 12:33:40Z] Verbose(0) Created operation named GetBySynchKey with signature PartyHandler::GetBySynchKey(String synchKey)
            62-[2019-08-21 12:33:40Z] Verbose(0) Created operation named GetByPartyNo with signature PartyHandler::GetByPartyNo(Int32 partyNo)
            62-[2019-08-21 12:33:40Z] Verbose(0) Created operation named GetByCvrcpr with signature PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p)
            62-[2019-08-21 12:33:40Z] Verbose(0) Created operation named GetByEmail with signature PartyHandler::GetByEmail(String email)
            62-[2019-08-21 12:33:40Z] Verbose(0) Created operation named Patch with signature PartyHandler::Patch(Int32 id, JsonPatchDocument patch)
            62-[2019-08-21 12:33:40Z] Verbose(0) Created operation named Delete with signature PartyHandler::Delete(Int32 id)
        62-[2019-08-21 12:33:40Z] Stop(1) Exiting PipelineRunner
        62-[2019-08-21 12:33:40Z] Start(1) Entering PipelineRunner: Executing contributor OperationFilterContributor.ProcessOperations
            62-[2019-08-21 12:33:40Z] Verbose(0) Found 5 operation(s) with a matching name.
            62-[2019-08-21 12:33:40Z] Verbose(0) Found 5 operation(s) with matching [HttpOperation] attribute.
            62-[2019-08-21 12:33:41Z] Verbose(0) Found 1 operations with correct attributes
        62-[2019-08-21 12:33:41Z] Stop(1) Exiting PipelineRunner
        62-[2019-08-21 12:33:41Z] Start(1) Entering PipelineRunner: Executing contributor OperationCodecSelectorContributor.ProcessOperations
            62-[2019-08-21 12:33:41Z] Information(0) Operation PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p) selected with 1 required members and 1 optional members, without request codec
            62-[2019-08-21 12:33:41Z] Information(0) Operation PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p) selected with 1 required members and 1 optional members, without request codec
            62-[2019-08-21 12:33:41Z] Information(0) Operation PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p) selected with 1 required members and 1 optional members, without request codec
            62-[2019-08-21 12:33:41Z] Information(0) Operation PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p) selected with 1 required members and 1 optional members, without request codec
            62-[2019-08-21 12:33:41Z] Information(0) Operation PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p) selected with 1 required members and 1 optional members, without request codec
            62-[2019-08-21 12:33:41Z] Information(0) Operation PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p) selected with 1 required members and 1 optional members, without request codec
        62-[2019-08-21 12:33:41Z] Stop(1) Exiting PipelineRunner
        62-[2019-08-21 12:33:41Z] Start(1) Entering PipelineRunner: Executing contributor OperationHydratorContributor.ProcessOperations
            62-[2019-08-21 12:33:41Z] Information(0) Operation PartyHandler::GetByCvrcpr(String cvrcpr, String cvr_p) was selected without a codec.
        62-[2019-08-21 12:33:41Z] Stop(1) Exiting PipelineRunner
        62-[2019-08-21 12:33:41Z] Start(1) Entering PipelineRunner: Executing contributor OperationInterceptorContributor.WrapOperations
        62-[2019-08-21 12:33:41Z] Stop(1) Exiting PipelineRunner
        62-[2019-08-21 12:33:41Z] Start(1) Entering PipelineRunner: Executing contributor OperationInvokerContributor.ExecuteOperations
The program '[33232] w3wp.exe' has exited with code 0 (0x0).
The program '[33232] w3wp.exe: Program Trace' has exited with code 0 (0x0).
