### ISSUE TITLE
OpenRasta Legacy Code

### ISSUE THREAD

**Issue by MZap** [openrasta/openrasta-core#192]
We are running a very old version of OpenRasta and upgrading is not a feasible task, when looking for the code we noticed the repo was empty. Is it possible to get the code for the versions listed below? Looks like we can get code from the tag. The link on the website pointed to an empty repo

<package id="openrasta-core" version="2.5.63" targetFramework="net451" />
  <package id="openrasta-hosting-aspnet" version="2.5.25" targetFramework="net40" />
  <package id="openrasta-razor" version="2.5.16" targetFramework="net40" />

**Comment by serialseb** [comment]
No references below, the repo is tagged. If you're running on a very old version before 2.1 you'd have to trawl through history.

I don't provide support for versions that are >10 years old for free, but we can discuss a commercial contract should you require assistance.

**Comment by serialseb** [comment]
Going through some of other issues, there is still the old repo at https://github.com/openrasta/archived-openrasta-legacy
think that'a s copy of the old svn repo so that may help somehow

**Comment by serialseb** [comment]
I'm going to go ahead and close this issue as it's been inactive for a while. If you feel there's more help that can be provided, do shout.
