### ISSUE TITLE
URL matching is case-sensitive

### ISSUE THREAD

**Issue by hanksjosholo** [openrasta/openrasta-core#204]
URL matching is currently case-sensitive.  If I register an endpoint for `/healthcheck`, it will not match if the URL is `/healthCheck`.

This appears to be a casualty of an inadvertent change to the `UriTemplate.Match()` function during a refactor in [this](https://github.com/openrasta/openrasta-core/commit/33e3c3957db347e59495d20bfe1f7601e22e3919) commit. 

I've created https://github.com/openrasta/openrasta-core/pull/203 to fix this, and it includes a unit test.

**Comment by serialseb** [comment]
Added proposed change, can merge after that

**Comment by hanksjosholo** [comment]
@serialseb Thanks for the quick merge!
