### ISSUE TITLE
Required HTTP headers are not generate by the InMemoryHost

### ISSUE THREAD

**Issue by serialseb** [openrasta/openrasta-core#21]
Required fields, usually generate by http clients and hosting servers, are not present in InMemoryRequest and InMemoryResponse.

On `InMemoryRequest`:
 - Host which should default to whatever the base URI is for the memory host, which I think is http://localhost. Bonus points for making it overridable

On `InMemoryResponse`, but only *after* processing has been done in case someone already wrote a value
 - Date in proper rfc822 format

**Comment by powelli13** [comment]
Hey there! I'm interested in picking up this issue. As far as I can tell it still needs resolving but I wanted to check in and see if there's anything I should know before starting on this one?
Thanks!

**Comment by serialseb** [comment]
That's awesome to hear! 
Don't hesitate to ping us on the openrasta room in our slack on http://slack.httpapis.com
Request-side it's the Host header, response-side is Date. Only gotcha with date is ensuring the date value is formatted correctly, aka 1 second resolution only and GMT only.
