### ISSUE TITLE
null returned from handlers to return different response codes

### ISSUE THREAD

**Issue by MarkKharitonov** [openrasta/openrasta-core#22]
Today, a GET handler must explicitly return an `OperationResult.NotFound` instance, because `null` is not automatically treated as 404. This makes handler signatures less type safe.

For instance, instead of the strongly typed:

```
public MyResource Get(int id) { ... }
```

one has to declare the following weakly typed method:

```
public OperationResult Get(int id) { ... }
```

Furthermore, in some cases, 415 is returned (when the pipeline resumes in an error condition) and that needs fixing too.

**Comment by serialseb** [comment]
Hi!

Thanks for contributing, it's awesome! 😎

After reviewing, the proposed features around OperationResult<T> are unlikely to make it at this stage, and current code ensures that `null` ResponseResource are treated as a 204 for poco handlers, and as Content-Length: 0 on other response status codes.

We are trying to keep our backlog fresh, and as this has not been updated for a while, I'm closing this issue. If you feel this was closed by mistake, or that it is still relevant, don't hesitate to comment and reopen it, and we'll re-evaluate.

Live long, and proper! 🖖🏽
