### ISSUE TITLE
Incorrect HTTP status code when a Codec's ReadFrom() throws

### ISSUE THREAD

**Issue by nmosafi** [openrasta/openrasta-core#8]
When an exception is thrown from a Codec's ReadFrom() method, OpenRasta currently returns to the client an Http 405 Method Not Allowed status code.

I think this is the incorrect status code, perhaps it should be 406 Not Acceptable to indicate there's something wrong with the payload.

**Comment by serialseb** [comment]
I'll assume that 400 is more often the right case than 500. Test added.
