### ISSUE TITLE
The WrapperStream should expose the underlying stream to enable efficient compression pipeline contributor implementation.

### ISSUE THREAD

**Issue by MarkKharitonov** [openrasta/openrasta-core#9]
A compression code is likely to be more efficient if `context.Response.Entity` exposed the actual underlying stream in addition to the `WrapperStream` instance.

This is because the underlying stream in most of the cases is a `MemoryStream` instance. This way, if the raw data buffer is needed, one will not have to copy bytes from the stream to a new buffer, but utilize the `MemoryStream.GetBuffer()` method to get the original buffer directly.

**Comment by serialseb** [comment]
Hi there.

Thanks for reporting this issue! It's awesome of you to have taken the time.

This issue has been superseded by  #101, so in the interest of keeping our backlog lean ⛅, I'm closing the issue in favour of the other one.

If you feel this is not right, don't hesitate to comment and/or reopen the issue.

Thanks!
