### ISSUE TITLE
Authentication via pipeline contributors - I think the pattern is broken?

### ISSUE THREAD

**Issue by dylanbeattie** [openrasta/openrasta-core#90]
I've duplicated the approach taken in the DigestAuthorizerContributor to implement BasicAuthorizerContributor, but I think the pattern used in the Digest implementation is broken. Specifically, I'm now getting prompted for credentials even when accessing resources that are not decorated with the RequiresAuthentication attribute.

Specifically - I don't think the authorization contributor should EVER be returning OperationResult.NotAuthorized - because authorization for the resource is controlled by the `RequiresAuthentication` attribute on the handler. I think the AuthorizerContributor should just check the headers and (if possible) set Context.User.Identity, but should ALWAYS return PipelineContinuation.Continue - because at this point, the authorizer doesn't know whether the request is for a secure resource or not... and then the RequiresAuthentication attribute should return the HTTP Unauthorized response and end the pipeline.

Make sense? Is it worth updating the authorizers to reflect this pattern, or have I missed something?

**Comment by dylanbeattie** [comment]
Proposed fix in https://github.com/openrasta/openrasta-core/pull/91

**Comment by holytshirt** [comment]
Without going through the code in detail, should have time this coming tuesday. @serialseb would be able to answer this better than me

**Comment by holytshirt** [comment]
@dylanbeattie yes I agree with you.
`AuthenticationContributor` should just check the headers, set `context.User` and `PipelineContinuation.Continue`

No you haven't missed anything. Just old uncared for part of the code base.
We use our own home rolled oAuthContributor at huddle.

**Comment by holytshirt** [comment]
I think the `RequiresAuthentication` attribute should return `new OperationResult.Unauthorized()` and another contributor `ChallengerContributor ` will write the challenge. The reason be is you can return 401 with a result, which you need to serialize via a codec or do other things. Ending the pipeline straight away will short cut the pipeline.

I need to extract this out into it's own library as it will be easier to refactor and clean up. Maybe a small xmas project

**Comment by serialseb** [comment]
Hi!

Thanks for contributing, it's awesome! 😎

After reviewing, Authentication may be brought back later, but in the meantime it's been removed and obsoleted. A placeholder authentication contributor has been readded in release 2.5.1050, so that code won't break.

We are trying to keep our backlog fresh, and as this has not been updated for a while, I'm closing this issue.If you feel this was closed by mistake, or that it is still relevant, don't hesitate to comment and reopen it, and we'll re-evaluate.

Live long, and proper! 🖖🏽
