### ISSUE TITLE
OpenID Connect with openrasta?

### ISSUE THREAD

**Issue by norcis** [openrasta/openrasta-core#94]
Is some of the projects I still use OpenRasta with Basic Authentication. I would like to move to OAuth2 with OpenID connect (eg. using identityserver4) but can't find many oAuth examples with newest openrasta-core.  Any reference where to start are welcome.

**Comment by holytshirt** [comment]
Hi @norcis you would have to write a contributor which you plug into the pipeline, give me a couple of days and I'll put a basic skeleton of one together for you

**Comment by norcis** [comment]
Hi @holytshirt Any news on sample? Thanks.

**Comment by norcis** [comment]
Hi. Few months passed. Any chances on sample?

**Comment by serialseb** [comment]
I believe a bunch of people did that.

That said, with owin in an asp.net pipeline, you can probably do what you want without having to implement this yourself.

A code sample would be pretty awesome though @holytshirt  :)

**Comment by serialseb** [comment]
Hi!

Thanks for contributing, it's awesome! 😎

After reviewing, this does not seem to be a core development issue. We're always on the lookout for good ideas, and this would be a great place for the community to step in.

We are trying to keep our backlog fresh, and as this has not been updated for a while, I'm closing this issue.  If you feel this was closed by mistake, or that it is still relevant, don't hesitate to comment and reopen it, and we'll re-evaluate.

Live long, and proper! 🖖🏽
